#ifndef CONFIGERROR_HPP
#define CONFIGERROR_HPP

#include "../core/utils.hpp"

enum ConfigErrorCode {
    ERR_AUTH_FILE_NOT_FOUND,
    ERR_CGI_SCRIPT_MISSING_DOLLAR_PREFIX,
    ERR_DUPLICATE_CGI_ENV_KEY,
    ERR_DUPLICATE_DEFAULT_ERROR_PAGE_BLOCK,
    ERR_DUPLICATE_DEFAULT_MIME_TYPE,
    ERR_DUPLICATE_GLOBAL_CGI_BLOCK,
    ERR_DUPLICATE_GLOBAL_CGI_MAPPING,
    ERR_DUPLICATE_HEADER_BLOCK,
    ERR_DUPLICATE_MIME_EXTENSION,
    ERR_DUPLICATE_SERVER_PORT,
    ERR_DUPLICATE_SERVER_TIMEOUT,
    ERR_DUPLICATE_TYPE_BLOCK,
    ERR_EMPTY_SERVER_BLOCK,
    ERR_FILE_NOT_EXECUTABLE,
    ERR_FILE_NOT_READABLE,
    ERR_HEADER_DEFINED_AFTER_ROUTE,
    ERR_INVALID_CGI_ENV_EMPTY_KEY_OR_VALUE,
    ERR_INVALID_CGI_ENV_FORMAT,
    ERR_INVALID_CGI_ENV_KEY,
    ERR_INVALID_CGI_ENV_KEY_VALUE,
    ERR_INVALID_CGI_ENV_MISSING_CLOSE_PAREN,
    ERR_INVALID_CGI_ENV_MISSING_EQUAL,
    ERR_INVALID_CGI_ENV_MULTIPLE_DECLARATIONS,
    ERR_INVALID_CGI_ENV_TRAILING_CHARS,
    ERR_INVALID_CGI_EXTENSION_LINE,
    ERR_INVALID_CGI_INLINE_ENV_SYNTAX,
    ERR_INVALID_CGI_TIMEOUT_RANGE,
    ERR_INVALID_ERROR_PAGE_FORMAT,
    ERR_INVALID_ERROR_PAGE_MAPPING,
    ERR_INVALID_ERROR_PAGE_STATUS_CODE,
    ERR_INVALID_ERROR_PAGE_STATUS_CODE_FORMAT,
    ERR_INVALID_ERROR_PAGE_STATUS_CODE_RANGE,
    ERR_INVALID_FILE_PATH,
    ERR_INVALID_GLOBAL_BLOCK_LOCATION,
    ERR_INVALID_GLOBAL_CGI_EXECUTABLE_PATH_WHITESPACE,
    ERR_INVALID_GLOBAL_CGI_EXTENSION_CHAR,
    ERR_INVALID_GLOBAL_CGI_EXTENSION_WHITESPACE,
    ERR_INVALID_GLOBAL_CGI_MAPPING_SYNTAX,
    ERR_INVALID_GLOBAL_CGI_MAPPING_VALUE,
    ERR_INVALID_HEADER_COLON_COUNT,
    ERR_INVALID_HEADER_FORMAT,
    ERR_INVALID_HEADER_MISSING_COLON,
    ERR_INVALID_HEADER_NAME,
    ERR_INVALID_HEADER_VALUE,
    ERR_INVALID_MAX_BODY_SIZE_VALUE_SYNTAX,
    ERR_INVALID_MIME_EXTENSION_CHAR,
    ERR_INVALID_MIME_MAPPING_SYNTAX,
    ERR_INVALID_MIME_MAPPING_VALUE,
    ERR_INVALID_MIME_TYPE_CHAR,
    ERR_INVALID_MIME_TYPE_FORMAT,
    ERR_INVALID_ROUTE_RULE_ADDITIONAL_INFO_FORMAT,
    ERR_INVALID_ROUTE_RULE_ADDITIONAL_INFO_SYNTAX,
    ERR_INVALID_SERVER_CONFIG_LINE,
    ERR_INVALID_SERVER_PORT,
    ERR_INVALID_SERVER_RESPONSE_TIME,
    ERR_INVALID_TOP_LEVEL_FORMAT,
    ERR_INVALID_UNSIGNED_INT_LEADING_ZERO,
    ERR_INVALID_WILDCARD_MAPPING,
    ERR_MAX_BODY_SIZE_OUT_OF_RANGE,
    ERR_MIME_EXTENSION_COUNT_MISMATCH,
    ERR_MISSING_DEFAULT_MIME_TYPE,
    ERR_MISSING_GLOBAL_CGI_MAPPING_OPERATOR,
    ERR_MISSING_MIME_MAPPING_OPERATOR,
    ERR_NOT_REGULAR_FILE,
    ERR_REQUIRED_SERVER_BLOCK_MISSING,
    ERR_REQUIRED_TYPE_BLOCK_MISSING,
    ERR_TIMEOUT_DEFINED_AFTER_ROUTE,
    ERR_UNDEFINED_GLOBAL_CGI_EXTENSION,
    ERR_UNDEFINED_ROUTE_OPERATOR,
    ERR_UNKNOWN_CONFIG_ERROR
};

class ConfigError {
  private:
    static std::string to_string(std::size_t value);

  public:
    static std::string make(const std::string& line, ConfigErrorCode code);
    static std::string make(const std::string& line, const std::string& target,
                            ConfigErrorCode code);

    static std::string make(const std::string& line,
                            const std::string& message);
    static std::string make(const std::string& line, const std::string& target,
                            const std::string& message);

    static std::string file_descriptor(const std::string& reason);
    static std::string add_line_number(std::size_t        line_number,
                                       const std::string& message);
};

#endif
