# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaejo <jaejo@student.42gyeongsan.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/01 16:11:45 by jaejo             #+#    #+#              #
#    Updated: 2025/05/31 16:12:28 by jaejo            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc
CFLAGS =
#CFLAGS = -Wall -Wextra -Werror -I.

NAME = minirt

FREE_SRCS = ./free/free.c \

PRINT_SRCS = ./print/write_color.c \

TRACE_SRCS = ./trace/trace.c ./trace/hit_sphere.c ./trace/phong_lighting.c \

SCENE_SRCS = ./scene/scene.c ./scene/object_utils.c ./scene/object_create.c \
			./scene/file_init.c ./scene/file_data_check.c ./scene/file_check_utils.c \

VEC_UTILS_SRCS = ./vec/make_vec_utils.c ./vec/vec_minus_utils.c ./vec/vec_mult_div_utils.c \
				 ./vec/vec_operator_utils.c ./vec/vec_plus_utils.c \

SRCS = ./main.c $(PRINT_SRCS) $(VEC_UTILS_SRCS) $(TRACE_SRCS) $(SCENE_SRCS) $(FREE_SRCS)

OBJS = $(SRCS:.c=.o)

all : $(NAME)

$(NAME) : $(OBJS)
	$(MAKE) -C ./ft_printf 
#$(MAKE) -C ./minilibx-linux
	$(CC) $(CFLAGS) $(OBJS) -L./ft_printf -lftprintf -lm -o $(NAME)
#$(CC) $(CFLAGS) $(OBJS) -L./ft_printf -lftprintf -L./minilibx-linux -lmlx -lXext -lX11 -lm -o $(NAME)

%.o : %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean :
	rm -f $(OBJS)
	$(MAKE) clean -C ./ft_printf

fclean : clean
	rm -f $(NAME)
	$(MAKE) fclean -C ./ft_printf

re : fclean all

.PHONY : all clean fclean re
